"""Create playerFav table

Revision ID: 755c193c2cd4
Revises: 6e9005802490
Create Date: 2024-02-04 22:32:41.500516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755c193c2cd4'
down_revision = '6e9005802490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playerFav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('kd_ratio', sa.Float(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playerFav')
    # ### end Alembic commands ###
