"""empty message

Revision ID: ccde861b56c4
Revises: 68261f52cb3c
Create Date: 2024-02-01 15:28:08.335042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccde861b56c4'
down_revision = '68261f52cb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('street_address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_constraint('user_profile_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('name')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_profile_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('street_address')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
